Update bundle and team ID for production
flyve-mdm/fusioninventory-ios pull request #38
Opened 2017-07-19 16:16 UTC by hectorerb

This PR updates bundle and team id for production

Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory-agent/issues/37

2017-07-19 16:24 UTC, rafaelje commented on fastlane/metadata/trade_representative_contact_information/country.txt
> -Venezuela
Are you using this information to fill the store? you need change it with Flyve information

2017-07-19 17:07 UTC, ajsb85 requested changes
Error on Travis CI `shell_session_update: command not found`

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/Fastfile
>      # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
Could you activate Slack?
To send notification to our dev chatroom.

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/en-US/privacy_url.txt
> -
https://flyve-mdm.com/privacy-policy/

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/review_information/email_address.txt
> -
apps@teclib.com

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/review_information/phone_number.txt
> -
+330179970278

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/trade_representative_contact_information/city_name.txt
> -Maracay
Paris

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/trade_representative_contact_information/address_line1.txt
> -Mata Redonda 2da Transversal
11 rue de Cambrai

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/trade_representative_contact_information/postal_code.txt
> -2103
75019

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/trade_representative_contact_information/trade_name.txt
> -s42, C.A.
Teclib

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/trade_representative_contact_information/country.txt
> -Venezuela
France

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/review_information/first_name.txt
> -
Alexander

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/review_information/last_name.txt
> -
Salas

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/en-US/support_url.txt
> -
http://support.teclib.com/

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/en-US/subtitle.txt
> -
Mobile device management

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/en-US/promotional_text.txt
> -
Flyve MDM is a Mobile device management software that enables you to secure and manage all the mobile devices of your business or family via a web-based console.

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/en-US/marketing_url.txt
> -
https://flyve-mdm.com/

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/en-US/keywords.txt
> -
agent, inventory-management, flyve-mdm

2017-07-19 17:07 UTC, ajsb85 commented on fastlane/metadata/copyright.txt
> -
May this one: `© Teclib' 2015-2017 | Flyve MDM®`

2017-07-19 17:33 UTC, hectorerb commented on fastlane/Fastfile
>      # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
yes, it's possible

2017-07-19 17:37 UTC, hectorerb commented on fastlane/metadata/en-US/privacy_url.txt
> -
Not necessary because the metadata was removed from fastlane

2017-07-19 17:37 UTC, hectorerb commented on fastlane/metadata/review_information/email_address.txt
> -
Not necessary because the metadata was removed from fastlane

2017-07-19 17:37 UTC, hectorerb commented on fastlane/metadata/review_information/phone_number.txt
> -
Not necessary because the metadata was removed from fastlane

2017-07-19 17:37 UTC, hectorerb commented on fastlane/metadata/trade_representative_contact_information/city_name.txt
> -Maracay
Not necessary because the metadata was removed from fastlane

2017-07-19 17:37 UTC, hectorerb commented on fastlane/metadata/trade_representative_contact_information/postal_code.txt
> -2103
Not necessary because the metadata was removed from fastlane

2017-07-19 17:37 UTC, hectorerb commented on fastlane/metadata/trade_representative_contact_information/trade_name.txt
> -s42, C.A.
Not necessary because the metadata was removed from fastlane

2017-07-19 17:37 UTC, hectorerb commented on fastlane/metadata/review_information/first_name.txt
> -
Not necessary because the metadata was removed from fastlane

2017-07-19 17:37 UTC, hectorerb commented on fastlane/metadata/review_information/last_name.txt
> -
Not necessary because the metadata was removed from fastlane

2017-07-19 17:37 UTC, hectorerb commented on fastlane/metadata/en-US/support_url.txt
> -
Not necessary because the metadata was removed from fastlane

2017-07-19 17:38 UTC, hectorerb commented on fastlane/metadata/en-US/subtitle.txt
> -
Not necessary because the metadata was removed from fastlane

2017-07-19 17:38 UTC, hectorerb commented on fastlane/metadata/en-US/promotional_text.txt
> -
Not necessary because the metadata was removed from fastlane

2017-07-19 17:38 UTC, hectorerb commented on fastlane/metadata/en-US/marketing_url.txt
> -
Not necessary because the metadata was removed from fastlane

2017-07-19 17:38 UTC, hectorerb commented on fastlane/metadata/en-US/keywords.txt
> -
Not necessary because the metadata was removed from fastlane

2017-07-19 17:38 UTC, hectorerb commented on fastlane/metadata/copyright.txt
> -
Not necessary because the metadata was removed from fastlane

2017-07-20 08:26 UTC, ajsb85 approved these changes
Reviewed

2017-07-20 08:26 UTC, merged